package learnitytms;

import org.grlea.log.*;
import java.util.*;
import org.directwebremoting.*;
import javax.servlet.http.*;

public class tms
{
    public static final SimpleLogger log;
    
    public void UpdateEmpProfle(final String emp_id) {
        DataBaseLayer.updateEmployeeProfileFromJob(emp_id);
    }
    
    public String getInformation(final String employee_id, final String role_id) {
        final Calendar calendar = new GregorianCalendar();
        final Date trialTime = new Date();
        calendar.setTime(trialTime);
        final String[] months = { "January", "Feburary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" };
        final String strTime = calendar.get(10) + ":" + calendar.get(12);
        final String strDate = months[calendar.get(2)] + " " + calendar.get(5) + ", " + calendar.get(1);
        String html = "";
        System.out.println("employee_id =" + employee_id);
        System.out.println("role_id =" + role_id);
        final String strEmpName = DataBaseLayer.getUserName(employee_id);
        final Vector<String> vSkillGap = DataBaseLayer.getSkillGap(employee_id, role_id);
        System.out.println("vSkillGap =" + vSkillGap);
        if (vSkillGap != null) {
            int i;
            String str;
            String str2;
            String str3;
            String str4;
            String str5;
            String str6;
            String str7;
            String s1;
            String s2;
            String s3;
            String s4;
            String str8;
            String table1;
            String table2;
            for (i = 0, i = 0; i < vSkillGap.size(); ++i) {
                str = null;
                str = vSkillGap.elementAt(i);
                str2 = str.substring(0, str.indexOf(126));
                str3 = str.substring(str.indexOf(126) + 1);
                str4 = str3.substring(0, str3.indexOf(126));
                str5 = str3.substring(str3.indexOf(126) + 1);
                str6 = str5.substring(0, str5.indexOf(126));
                str7 = str5.substring(str5.indexOf(126) + 1);
                s1 = DataBaseLayer.getFamilyTitle(str2);
                s2 = DataBaseLayer.getSkillTitle(str4);
                s3 = DataBaseLayer.getLevelTitle(str6);
                s4 = DataBaseLayer.getLevelTitle(str7);
                str8 = DataBaseLayer.getLearningEvent(str2, str4, str6, str7);
                if (s1 == null) {
                    s1 = "-";
                }
                if (s2 == null) {
                    s2 = "-";
                }
                if (s3 == null) {
                    s3 = "-";
                }
                if (s4 == null) {
                    s4 = "-";
                }
                table1 = "";
                table1 = "<table border=\"1px\" width=\"800px\" align=\"center\"><tbody><tr><td colspan = \"2\"><b>Skill Gap Report for:</b> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" + strEmpName + "</td><td colspan=\"2\"><b>Employee Id:</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" + employee_id + "</td></tr>" + "<tr><td colspan = \"2\"><b>Generated By LearnITyTM TMS</b>&nbsp&nbsp&nbsp&nbsp</td><td colspan = \"2\">" + strTime + " - " + strDate + "</td></tr>" + "<tr><td width=\"25%\"><b>Skill Family</b></td><td width=\"25%\"><b>Skill</b></td><td width=\"25%\"><b width=\"25%\">Current Level</b></td><td width=\"25%\"><b>Desired Level</b></td></tr>" + "<tr><td width=\"25%\">" + s1 + "</td><td width=\"25%\">" + s2 + "</td><td width=\"25%\">" + s3 + "</td><td width=\"25%\">" + s4 + "</td></tr>" + "</tbody></table>";
                table2 = "";
                table2 = "<table border=\"1px\" width=\"800%\" align=\"center\"><tbody><tr><td>Skill Family</td><td>Skill</td><td>Current Level</td><td>Desired Level</td></tr><tr><td>" + s1 + "</td><td>" + s2 + "</td><td>" + s3 + "</td><td>" + s4 + "</td></tr>" + "</tbody></table>";
                html = table1;
            }
        }
        return html;
    }
    
    public String getUserIdFromSession() {
        final WebContext wctx1 = WebContextFactory.get();
        final HttpSession mysession = wctx1.getSession();
        final String user_id = (String)mysession.getAttribute("user_id");
        return user_id;
    }
    
    public String getDetails(final String user_id, final String Period_id, final String strProgramId) {
        String html = "";
        String div = "<div style= \"font-size:12px\">";
        String table = "";
        final Vector<String> vconrep = DataBaseLayer.getReportIntroduction(user_id, Period_id);
        if (vconrep != null) {
            final String strUserName = vconrep.elementAt(0);
            final String strPYear = vconrep.elementAt(1);
            final String strTCost = vconrep.elementAt(2);
            final String strTCredit = vconrep.elementAt(3);
            final String strTHour = vconrep.elementAt(4);
            div = div + "<p>Training Record for " + strUserName + " For the Period " + strPYear;
            div = div + "<p>Total Attended Hours: " + strTHour + "  Total Consumed Budget: Rs " + strTCost + "  Total Credit Obtained: " + strTCredit;
        }
        final Vector<String> vplanrep = DataBaseLayer.getPlanReport(user_id, Period_id);
        if (vplanrep != null) {
            final String strTCost2 = vplanrep.elementAt(0);
            final String strTCredit2 = vplanrep.elementAt(1);
            final String strTHour2 = vplanrep.elementAt(2);
            div = div + "<p><b>Total Planned Hours:</b> " + strTHour2 + "  <b>Total Planned Budget:</b> Rs " + strTCost2 + "  <b>Total Planned Credit:</b> " + strTCredit2 + "<br>";
        }
        div += "</div>";
        final Vector<String> vpg_us_pr = DataBaseLayer.getProgramDetForReport(user_id, Period_id, strProgramId);
        if (vpg_us_pr != null) {
            for (int i = 0; i < vpg_us_pr.size(); i += 10) {
                final String strhour = vpg_us_pr.elementAt(i + 2);
                final String strcost = vpg_us_pr.elementAt(i + 3);
                final String strcredit = vpg_us_pr.elementAt(i + 4);
                final String strstarttime = vpg_us_pr.elementAt(i + 5);
                final String strendtime = vpg_us_pr.elementAt(i + 6);
                final String strstartdate = vpg_us_pr.elementAt(i + 7);
                final String strenddate = vpg_us_pr.elementAt(i + 8);
                final String strcomment = vpg_us_pr.elementAt(i + 9);
                final Vector<String> vProgNames = DataBaseLayer.getApprovedProgramNames(user_id, Period_id);
                String select1 = "<select id=\"prog_id\" name=\"prog_id\">";
                for (i = 0; i < vProgNames.size(); i += 2) {
                    final String strProgId = vProgNames.elementAt(i);
                    final String strProgName = vProgNames.elementAt(i + 1);
                    select1 = select1 + "<option value=\"" + strProgId + "\">" + strProgName + "</option>";
                }
                select1 += "</select>";
                System.out.println("select1=4==" + select1);
                final String select2 = "<select id=\"attended\" name=\"attended\"><option value=Yes>Yes</option><option value=No>No</option></select>";
                final String select3 = "<select id=\"completed\" name=\"completed\"><option value=Yes>Yes</option><option value=No>No</option></select>";
                final String select4 = "<select id=\"attendedpre\" name=\"attendedpre\"><option value=Yes>Yes</option><option value=No>No</option></select>";
                final String select5 = "<select id=\"attendedpost\" name=\"attendedpost\"><option value=Yes>Yes</option><option value=No>No</option></select>";
                String optionResultPre = "";
                optionResultPre = "<select id=\"resultpre\" name=\"resultpre\">";
                Vector<String[]> vLevels;
                String[] str;
                for (vLevels = DataBaseLayer.getEvaluationLevels(), i = 0; i < vLevels.size(); ++i) {
                    str = vLevels.elementAt(i);
                    optionResultPre = optionResultPre + "<option value=\"" + str[0] + "\">" + str[1] + "</option>";
                }
                optionResultPre += "</option>";
                String optionResultPost = "";
                optionResultPost = "<select id=\"resultpost\" name=\"resultpost\">";
                for (i = 0; i < vLevels.size(); ++i) {
                    final String[] str2 = vLevels.elementAt(i);
                    optionResultPost = optionResultPost + "<option value=\"" + str2[0] + "\">" + str2[1] + "</option>";
                }
                optionResultPost += "</option>";
                table = (html = "<table width=\"100%\" style=\"font-size:11px;\" align=\"center\"><tr><td colspan=2>Select Program :</td><td colspan = 2>" + select1 + "</td><td>Attended :</td><td>" + select2 + "</td><td>Completed :</td><td>" + select3 + "</td><td></td></tr>" + "<tr><td>StartTime :</td><td>" + strstarttime + "</td><td>End Time :</td><td>" + strendtime + "</td><td>Start Date :</td><td>" + strstartdate + "</td><td>End Date :</td><td>" + strenddate + "</td></tr>" + "<tr><td>Hours :</td><td>" + strhour + "</td><td>Budget :</td><td>" + strcost + "</td><td>Credit :</td><td>" + strcredit + "</td><td>Comment</td><td><input type=\"textarea\" row = \"4\" coloum=\"12\" id=\"comment\" name=\"comment\">" + strcomment + "</input></td></tr>" + "</table>");
                final Vector<String> vprepost = DataBaseLayer.checkPrePost(user_id, Period_id, strProgramId);
                String strPre = null;
                String strPost = null;
                if (vprepost != null) {
                    for (i = 0; i < vprepost.size(); ++i) {
                        strPre = vprepost.elementAt(0);
                        strPost = vprepost.elementAt(1);
                        //strPreatt = vprepost.elementAt(2);
                        //strPreRes = vprepost.elementAt(3);
                        //strPostatt = vprepost.elementAt(4);
                        //strPostRes = vprepost.elementAt(5);
                    }
                }
                String tablepre = "";
                tablepre = "<table style=\"font-size:11px;\"><tr><td colspan=\"4\">Pre Evaluation : </td></tr><tr><td>Attended : </td><td>" + select4 + "</td><td>Result :</td><td>" + optionResultPre + "</td>" + "</tr></table>";
                String tablepost = "";
                tablepost = "<table style=\"font-size:11px;\"><tr><td colspan=\"4\">Post Evaluation : </td></tr><tr><td>Attended : </td><td>" + select5 + "</td><td>Result :</td><td>" + optionResultPost + "</td>" + "</tr></table>";
                if (strProgramId != null && !strProgramId.equals("null")) {
                    if (strPre != null && strPost != null) {
                        html = div + html + tablepre + tablepost;
                    }
                    if (strPre != null && strPost == null) {
                        html = div + html + tablepre;
                    }
                    if (strPost != null && strPre == null) {
                        html = div + html + tablepost;
                    }
                }
            }
        }
        return html;
    }
    
    public static synchronized void updateRecord(final String struserid, final String strprogramid, final String strperiodid, String strattended, String strcompleted, final String comment, String strAttendedPre, final String strResultsPre, String strAttendedPost, final String strResultsPost) {
        final WebContext wctx1 = WebContextFactory.get();
        final HttpSession mysession = wctx1.getSession();
        final String strCreatedBy = (String)mysession.getAttribute("user_id");
        System.out.println("strCreatedBy =" + strCreatedBy);
        if (strattended.equals("Yes")) {
            strattended = "Y";
        }
        if (strattended.equals("No")) {
            strattended = "N";
        }
        if (strcompleted.equals("Yes")) {
            strcompleted = "Y";
        }
        if (strcompleted.equals("No")) {
            strcompleted = "N";
        }
        if (strAttendedPre.equals("Yes")) {
            strAttendedPre = "Y";
        }
        if (strAttendedPre.equals("No")) {
            strAttendedPre = "N";
        }
        if (strAttendedPost.equals("Yes")) {
            strAttendedPost = "Y";
        }
        if (strAttendedPost.equals("No")) {
            strAttendedPost = "N";
        }
        DataBaseLayer.updateRecord(struserid, strprogramid, strperiodid, strattended, strcompleted, comment, strAttendedPre, strResultsPre, strAttendedPost, strResultsPost, strCreatedBy);
    }
    
    public static synchronized void deleteRecord(final String strUsrId, final String strProgram, final String strPeriod) {
        final WebContext wctx1 = WebContextFactory.get();
        final HttpSession mysession = wctx1.getSession();
        final String strCreatedBy = (String)mysession.getAttribute("user_id");
        DataBaseLayer.deleteRecord(strUsrId, strProgram, strPeriod, strCreatedBy);
    }
    
    public static synchronized void addEvaluation(final String program_id, final String evaluationId, final String typeId, final String date, final String sta_time, final String end_time) {
        DataBaseLayer.addEvaluation(program_id, evaluationId, typeId, date, sta_time, end_time);
    }
    
    public static synchronized void modifyEvaluation(final String program_id, final String evaluationId, final String typeId, final String date, final String sta_time, final String end_time) {
        DataBaseLayer.modifyEvaluation(program_id, evaluationId, typeId, date, sta_time, end_time);
    }
    
    public static synchronized void deleteEvaluation(final String program_id, final String evaluationId) {
        DataBaseLayer.deleteEvaluation(program_id, evaluationId);
    }
    
    public static synchronized String[] getEvaluation(final String program_id, final String eval_type) {
        String[] str = new String[5];
        str = DataBaseLayer.getEvaluation(program_id, eval_type);
        return str;
    }
    
    static {
        log = new SimpleLogger((Class)tms.class, true);
    }
}
